apiVersion: v1
kind: Service
metadata:
  name: almacen
  labels:
    app: rep
spec:
  clusterIP: None
  selector:      # tiene que coincidir con label definido en pod de StatefulSet
    app: rep  # Para dar de alta automaticamente en DNS a los PODS ligados
  ports:
  - port: 6000
    name: servidor-port
    protocol: TCP
    targetPort: 6000

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: r
spec:
  serviceName: almacen
  replicas: 2
  podManagementPolicy: Parallel   # por defecto seria OrderedReady (secuencial)
  selector:
    matchLabels:
      app: rep    # tiene que corresponder a .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: rep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: servidor
        image: localhost:5000/servidor:latest
        env:
        - name: MISUBDOMINIODNS
          value: almacen.default.svc.cluster.local
        - name: MINOMBREPOD		# primera replica r-0, segunda r-1, etc
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - servidor
        args:
        - $(MINOMBREPOD).$(MISUBDOMINIODNS):6000
        - r-0.$(MISUBDOMINIODNS):6000
        - r-1.$(MISUBDOMINIODNS):6000
#        - r-2.$(MISUBDOMINIODNS):6000
        ports:
        - containerPort: 6000
        volumeMounts:
        - name: fichero
          mountPath: ./
  volumeClaimTemplates:
    - metadata:
        name: fichero
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi


